[project]
name = "gitea_pkg"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "cloudformation_dataclasses",
]

[project.scripts]
gitea_pkg = "gitea_pkg.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["gitea_pkg"]

[tool.hatch.build.targets.sdist]
include = ["gitea_pkg/**/*.py", "gitea_pkg/resources/"]

[dependency-groups]
dev = [
    "mypy>=1.0",
    "pytest>=8.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
