[project]
name = "fn_foreach_ddb"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "cloudformation_dataclasses",
]

[project.scripts]
fn_foreach_ddb = "fn_foreach_ddb.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["fn_foreach_ddb"]

[tool.hatch.build.targets.sdist]
include = ["fn_foreach_ddb/**/*.py", "fn_foreach_ddb/resources/"]

[dependency-groups]
dev = [
    "mypy>=1.0",
    "pytest>=8.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
