[project]
name = "example_3"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "cloudformation_dataclasses",
]

[project.scripts]
example_3 = "example_3.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["example_3"]

[tool.hatch.build.targets.sdist]
include = ["example_3/**/*.py"]

[dependency-groups]
dev = [
    "mypy>=1.0",
]
