[project]
name = "codebuild_app_deploy"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "cloudformation_dataclasses",
]

[project.scripts]
codebuild_app_deploy = "codebuild_app_deploy.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["codebuild_app_deploy"]

[tool.hatch.build.targets.sdist]
include = ["codebuild_app_deploy/**/*.py", "codebuild_app_deploy/resources/"]

[dependency-groups]
dev = [
    "mypy>=1.0",
    "pytest>=8.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
