[project]
name = "rhel9_cfn_hup"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "cloudformation_dataclasses",
]

[project.scripts]
rhel9_cfn_hup = "rhel9_cfn_hup.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["rhel9_cfn_hup"]

[tool.hatch.build.targets.sdist]
include = ["rhel9_cfn_hup/**/*.py", "rhel9_cfn_hup/resources/"]

[dependency-groups]
dev = [
    "mypy>=1.0",
    "pytest>=8.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
