[project]
name = "template_1"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "cloudformation_dataclasses",
]

[project.scripts]
template_1 = "template_1.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["template_1"]

[tool.hatch.build.targets.sdist]
include = ["template_1/**/*.py"]

[dependency-groups]
dev = [
    "mypy>=1.0",
]
