[project]
name = "vpcflowlogs_main_cfn"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "cloudformation_dataclasses",
]

[project.scripts]
vpcflowlogs_main_cfn = "vpcflowlogs_main_cfn.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["vpcflowlogs_main_cfn"]

[tool.hatch.build.targets.sdist]
include = ["vpcflowlogs_main_cfn/**/*.py", "vpcflowlogs_main_cfn/resources/"]

[dependency-groups]
dev = [
    "mypy>=1.0",
    "pytest>=8.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
